spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Swagger-UI / OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Security Configuration
chargewise:
  jwt:
    # 256-bit or greater base64 key
    secret: dGhpc2lzYWJlYXV0aWZ1bHNlY3JldGtleWZvcmNoYXJnZXdpc2VpbmRpYWZ1bGxzdGFja2V2YXBwbGljYXRpb24yMDI2
    accessTokenExpirationMs: 3600000        # 1 hour
    refreshTokenExpirationMs: 2592000000      # 30 days
  seeding:
    station-count: 550
